### ISSUE TITLE
go-gin instrumentation will not output spans

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-go-contrib#609]
OTel Version: v0.18
Gin Version: 1.6.3

👋 I'm encountering a strange bug with the export pipeline and go-gin. Perhaps I'm holding it wrong, but I'm not able to have any spans exported either via OTLP GRPC or even the console exporter (see https://github.com/austinlparker/otel-rc-examples/blob/main/go/01/main.go for a repro). 

I do see spans appropriately being created in-memory, but they just never seem to make it to export. Interestingly enough, if I modify the provider to use `WithSyncer` rather than `WithBatcher` they _are_ exported.

**Comment by MrAlias** [comment]
It looks like you are shutting your tracer provider down right after you initialize:

https://github.com/austinlparker/otel-rc-examples/blob/e6e62abf1bf394719c5529286fd97e5b2774a98a/go/01/main.go#L55-L61

I'm guessing this works with the simple span processor because we were not propagating the shutdown command to the exporter for that span processor (which has been fixed on `main`).

**Comment by austinlparker** [comment]
Yeah I was curious about that so I tried removing the defer, it still doesn't output batched spans.

**Comment by austinlparker** [comment]
:facepalm: I was still having problems with it but it turned out to be a local issue. My bad.
